### PR TITLE
Merge brson's work into master

### PR DESCRIPTION
**Pull request by brson**
Obsoletes https://github.com/Diggsey/multirust-rs/pull/82 and https://github.com/Diggsey/multirust-rs/pull/85.

I apologize for the overwhelming number of patches here. I've addressed the comment about upgrades being broken in https://github.com/Diggsey/multirust-rs/pull/82, and tested on both linux and windows.

@Diggsey I'd like to get this merged into master and start iterating live. v2 manifests are in production now.

### CODE REVIEW

**Comment by brson** [comment]
@Diggsey Everything's green and I am eager to merge this. Can I?

**Comment by Diggsey** [comment]
Here goes...

**Comment by Ticki** [comment]
Awesome work, @brson!

**Comment by hauleth** [comment]
:+1:

**Comment by brson** [comment]
Woo! Thanks @Diggsey!

**Pull request merged**
