### PR TITLE
Run rustfmt over multirust

### PR DESCRIPTION
**Pull request by alexcrichton**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Rebased to the current master

**Comment by Diggsey** [comment]
It seems to leave tabs unconverted when they are inside a macro.

**Comment by alexcrichton** [comment]
Opened https://github.com/nrc/rustfmt/issues/545 and https://github.com/nrc/rustfmt/issues/544 and manually changed them for now.

**Comment by brson** [comment]
Since this is ancient, I'll just redo it soon. *shakes fist at tabs*

**Pull request closed without merging**
