### PR TITLE
style: Replace tabs by spaces

### PR DESCRIPTION
**Pull request by kamalmarhubi**

### CODE REVIEW

**Comment by Diggsey** [comment]
@brson I haven't merged this in yet because I didn't want to give you a load of merge conflicts, but it LGTM

**Comment by kamalmarhubi** [comment]
Sounds good. Definitely makes more sense to have this change deal with any conflicts!

**Comment by brson** [comment]
Huh, I wonder how I missed all this when I rustfmted. We can merge and I'll deal with the conflicts.

**Comment by kamalmarhubi** [comment]
@brson rustfmt didn't fix this, which surprised me.

**Comment by Diggsey** [comment]
It's probably the same bugs encountered in #16

**Pull request merged**
