### PR TITLE
Enable v2 manifest support

### PR DESCRIPTION
**Pull request by brson**
V2 manifests work. Let's turn them on.

### CODE REVIEW

**Comment by alexcrichton** [comment]
:pineapple:

**Comment by brson** [comment]
Not sure what the failure is.

**Comment by brson** [comment]
cc @Diggsey I've added a commit here that temporarily pins multirust-rs to nightly-2016-03-11 because of https://github.com/rust-lang/rust/issues/32247.

**Comment by brson** [comment]
Closing this PR to do admin work on my repo.

**Pull request closed without merging**
