### PR TITLE
Improve interface of multirust-doc

### PR DESCRIPTION
**Pull request by crumblingstatue**
Open the documentation index by default, and give access to more specific
docs through flags.

Ref #83

### CODE REVIEW

**Comment by brson** [comment]
While I do think this should open the index by default, I'm not comfortable encoding all these resources directly into multirust: the exact composition of the Rust docs is fairly fluid and will definitely change again.

I actually think the `doc` command is a bit of a misfeature for multirust - I'd much rather have a `cargo doc` subcommand that was much more aggressive about indexing and finding Rust documentation.

Can we make the minimal change of just opening the index instead of std?

**Comment by crumblingstatue** [comment]
> I'm not comfortable encoding all these resources directly into multirust: the exact composition of the Rust docs is fairly fluid and will definitely change again.

Which items do you think are the most likely to change? I think that at least the book, and the standard library documentation won't go anywhere, plus I'd like to have the most convenient way possible for opening the standard library docs, so I at least would like to keep the `--std` option if nothing else.

> I actually think the doc command is a bit of a misfeature for multirust - I'd rather have a cargo doc subcommand that was much more aggressive about indexing and finding Rust documentation.

Cargo already has a `doc` subcommand, but it is for generating documentation, not for opening the bundled Rust documentation.

Also, is/should Cargo be aware of where Rust is installed? Doesn't it just call the `rustc` command in `PATH`? Cargo would need to be aware of this information in order to find the docs.

**Comment by steveklabnik** [comment]
Yes, `cargo doc` is already about generating docs, and `cargo doc --open` opens the current crate's docs. I would also assume that `multirust` would be for rust's docs itself. I guess we could in theory make it more general, but it feels like a weird separation of concerns to me: `cargo` is about managing the current crate, `multirust` is about managing my Rust installation.

> Which items do you think are the most likely to change? I think that at least the book, and the standard library documentation won't go anywhere, plus I'd like to have the most convenient way possible for opening the standard library docs, so I at least would like to keep the --std option if nothing else.

Yes, I'm not aware of any intention to change at least `/std` and `/book`. The way the book gets generated may get pulled out-of-tree, but I would think that we wouldn't want to break all of these links by changing them, they've gotten a lot of google juice over the years.

**Comment by Diggsey** [comment]
> it feels like a weird separation of concerns to me

I think @brson's rationale is that multirust is not tied to a specific rust version, whereas cargo is, so if the location of the documentation *were* to change, it would be trivial to tell cargo about it, whereas multirust would have to know about both the old and new locations.

However, I think it's a problem that can be solved when (if) we come to it: for example, we could just add a file to the doc component which stores a mapping from "logical name" to file path, so that when we encounter `--[logical name]` it can be resolved to a path without multirust needing to be intelligent about the rust version, beyond "does it have this file? If not, use the old defaults".

**Comment by crumblingstatue** [comment]
Alright, only `--std` and `--book` are present now, and the tests pass. Anything else?

**Comment by brson** [comment]
Thanks @crumblingstatue!

**Pull request merged**
